### PR TITLE
[WIP] update setup docs

### LINKED ISSUE #697: Stress test the full CL setup documentation and improve it
- [x] Test [dev env](https://github.com/colouring-cities/colouring-london/blob/master/docs/setup-dev-environment.md) setup
    - At least some of this is automated when running `vagrant up` by [vm_provision.sh](https://github.com/colouring-cities/colouring-london/blob/master/provision/vm_provision.sh)
    - Can I just use [these steps](https://github.com/colouring-cities/colouring-london-config)?
- [ ] Test [prod env](https://github.com/colouring-cities/colouring-london/blob/master/docs/setup-production-environment.md) setup
- [x] Link to the above in README
- [x] Tidy the README's in `/etl`
- [ ] and `/migrations`
    - (perhaps integrate into a single manual on the main README)
- [ ] Move this [issue template](https://github.com/colouring-london/colouring-london/blob/master/.github/ISSUE_TEMPLATE/deploy.md) into [colouring-london-config](https://github.com/colouring-london/colouring-london-config) and refine as needed

### LINKED ISSUE #720: Update and better document local CL setup with OSM test polygons
Currently the`etl/get_test_polygons.py` script thows an error and looks like this occurs when using the latest osmnx package.

**To Reproduce**:
1. `cd etl`
2. `python get_test_polygons.py`

**Expected behavior**:
Downloads test data

**Error**:
```
2022-01-18 09:55:33 Configured OSMnx 1.1.2
2022-01-18 09:55:33 HTTP response caching is on
Traceback (most recent call last):
  File ".../colouring-london/etl/get_test_polygons.py", line 24, in <module>
    gdf = osmnx.footprints_from_point(point=point, dist=dist)
AttributeError: module 'osmnx' has no attribute 'footprints_from_point'. Did you mean: 'geometries_from_point'?
```

**To close**:
- [x] Either update the script to work for the latest `osmnx` package or control the version to one that works
    - works with `osmnx==0.13`
- [x] Update `etl/README.md`

### LINKED ISSUE #766: Deployment scripts and instructions not working (deprecated?)
**Describe the problem**
Our team has tried installing Colouring-London locally on our servers to assess the ease of deployment and customisation (for a new geographical area) and possibly recommend adoption to our partners. We have tried vagrant up and the provision script and other instructions but the installation process fails at various stages.  

**To Reproduce**

We tried vagrant up but it fails from the start.

We also tried to the vm_provision script in a Ubuntu 20.04 docker container but first npm packages would fail to install then some python scripts (python get_test_polygons.py) failed with imports.

**Expected behavior**

Local VM ready to be provisioned & configured, web and backend services running properly.

**Comments**

I can provide more details about what we tried and what fails exactly. But a more general question for us is whether the instructions and provisioning scripts are still up to date and supposed to work with the latest version of the repository?

If not we'd be interested to learn if and when you are planning to update them.

Thanks in advance for your help !

### PR DESCRIPTION
**Pull request by edwardchalstrey1**
test branch

### CODE REVIEW

**Comment by edwardchalstrey1** [comment]
closing as superseded by #776
