### ISSUE TITLE
Update and better document local CL setup with OSM test polygons

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-london#720]
Currently the`etl/get_test_polygons.py` script thows an error and looks like this occurs when using the latest osmnx package.

**To Reproduce**:
1. `cd etl`
2. `python get_test_polygons.py`

**Expected behavior**:
Downloads test data

**Error**:
```
2022-01-18 09:55:33 Configured OSMnx 1.1.2
2022-01-18 09:55:33 HTTP response caching is on
Traceback (most recent call last):
  File ".../colouring-london/etl/get_test_polygons.py", line 24, in <module>
    gdf = osmnx.footprints_from_point(point=point, dist=dist)
AttributeError: module 'osmnx' has no attribute 'footprints_from_point'. Did you mean: 'geometries_from_point'?
```

**To close**:
- [x] Either update the script to work for the latest `osmnx` package or control the version to one that works
    - works with `osmnx==0.13`
- [x] Update `etl/README.md`

**Comment by tomalrussell** [comment]
For ref - https://osmnx.readthedocs.io/en/stable/osmnx.html?highlight=geometries_from_point#osmnx.geometries.geometries_from_point
